# This is a TOML document. Boom
mq = "kafka"
[discovery]
    nodes = ["127.0.0.1:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]

[nats]
    topic = "goim-push-topic"
    broker = "nats://127.0.0.1:4222"